- [from sklearn.preprocessing import PolynomialFeatures](#poly)
<br>[polynomial_converter = PolynomialFeatures(degree=, interaction_only=, include_bias=)](#poly)
<br>[polynomial_converter.fit(X)](#poly)
<br>[poly_features = polynomial_converter.transform(X)](#poly)
<br>or [polynomial_converter.fit_transform(X)](#poly)
-[polynomial_converter.get_feature_names_out()](#poly)

---

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

What we're actually going to do is first separate out our features from our label and then use preprocessing to create changes or new features from our original three features.

In [4]:
X = df.drop('sales', axis=1)
y = df['sales']

Now it's time for polynomial regression. Again, we do this with the __preprocessing library__ from Scikit_Learn.

In [5]:
from sklearn.preprocessing import PolynomialFeatures

The way PolynomialFeatures works is it's in the same framework as just something like LinearRegression or any other model within sklearn. You create an instance of PolynomialFeatures and then you can actually fit to your data set.

In [6]:
polynomial_converter = PolynomialFeatures(degree=2, include_bias=False)

The parameters:
- __degree__ - to what order do you want to take the polynomial?
- __interaction_only__ - whether you want only the interaction terms.
- __include_bias__ - if you include the bias term, that's going to add in the array column of one values.

What polynomial_convertor is expecting is to be fit onto a data set, and fitting in this case means is it's going to grab and analyze all the feature values. It's not actually going to transform anything until you ask for it.

In [7]:
polynomial_converter.fit(X)

PolynomialFeatures(include_bias=False)

__Keep in mind__, we don't actually need to split this into a training set or test set yet because this is not our machine learning model, it's just a feature converter.

However, if we actually want to transform it, then

In [8]:
polynomial_converter.transform(X)

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [9]:
polynomial_converter.transform(X).shape

(200, 9)

In [10]:
X.shape

(200, 3)

In [11]:
X.iloc[0]

TV           230.1
radio         37.8
newspaper     69.2
Name: 0, dtype: float64

In [12]:
poly_features = polynomial_converter.transform(X)

In [13]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

So the first three values are your original x1, x2, x3. So it makes sense now that we have nine terms, the original three, the three possible interaction terms and then the three possible squared terms.

And essentially what we're going to do is train on poly_features and do our train_test_split on poly_features as if it was our original data set.

Because it's so common to fit and transform on the exact same data set, there's also a __`fit_transform() method`__.

In [14]:
polynomial_converter.fit_transform(X) 

# it essentially does both steps at the same time

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [15]:
polynomial_converter.get_feature_names_out()

array(['TV', 'radio', 'newspaper', 'TV^2', 'TV radio', 'TV newspaper',
       'radio^2', 'radio newspaper', 'newspaper^2'], dtype=object)

---

Well, the advertising data set is an example that we show, using polynomial regression gives better performance than just linear regression, due to interaction between the terms.

include_bias = True _ this would just add the intercept term to the power of 0, which is 1. Not really needed since the linear regression we call on this will have the bias term.

__DO NOT confuse__ the terms __"multiple linear regression"__ with __"polynomial regression"__. Multiple means more than 1 x feature. Polynomial means you are raising those multiple features to x^2 x^3 etc...