In [1]:
import numpy as np

__Exercise__: Create a small 5×5 array to represent a simple image (maybe a diagonal line of 255s on a background of 0s). Print out the array and verify the positions of high values form the diagonal. This simulates creating a simple image pattern with numpy.

In [2]:
a = np.diag([255] * 5)

In [3]:
a

array([[255,   0,   0,   0,   0],
       [  0, 255,   0,   0,   0],
       [  0,   0, 255,   0,   0],
       [  0,   0,   0, 255,   0],
       [  0,   0,   0,   0, 255]])

In [4]:
# Verify positions of 255

for i in range(a.shape[0]):
    if a[i, i] == 255:
        print(f'255 found at position {i}, {i}')

255 found at position 0, 0
255 found at position 1, 1
255 found at position 2, 2
255 found at position 3, 3
255 found at position 4, 4


---

In [5]:
b = np.zeros((5, 5), dtype=int)
np.fill_diagonal(b, 255)        # modifies the input array in-place, it does not return a value
b

array([[255,   0,   0,   0,   0],
       [  0, 255,   0,   0,   0],
       [  0,   0, 255,   0,   0],
       [  0,   0,   0, 255,   0],
       [  0,   0,   0,   0, 255]])

---

__NumPy arrays__ are `homogeneous`, meaning `every element must be the same type`.

---

In [6]:
students = np.array([
    [1, 85, 78],
    [2, 90, 88],
    [3, 75, 85]
], dtype=np.int32)

students

array([[ 1, 85, 78],
       [ 2, 90, 88],
       [ 3, 75, 85]])

In [7]:
students[:, 1].mean()   # mean of second column (Math scores)

83.33333333333333

---

__Real-World Example (Loading CSV data):__ You might have a CSV file with rows of data. While the pandas library is often used for tabular data, NumPy can also load simple numeric data. For instance, if data.csv contains:

In [8]:
# height,weight,age
# 170,65,25
# 160,50,30
# 180,80,22

We can load it with NumPy (using `genfromtxt` or `loadtxt`):

In [9]:
data = np.loadtxt('data.csv', delimiter=',', skiprows=1)
data

array([[170.,  65.,  25.],
       [160.,  50.,  30.],
       [180.,  80.,  22.]])

In [10]:
# Notice by default loadtxt gave floats; we can specify dtype=int if we want integers.

---
---

### Key Linear Algebra Concepts in Machine Learning
---

#### 1. Vectors

Description: In mathematics, __a vector__ is an ordered list of numbers. Geometrically, you can think of a vector as a point in space (like a coordinate) or an arrow from the origin to that point. For example, [3, 5] in 2D represents a point 3 units along the x-axis and 5 units along the y-axis. Vectors have a _magnitude_ (length) and _direction_. In linear algebra, vectors are often written as column vectors (like a column of numbers), but in NumPy we usually use 1D arrays to represent them.

In data science, a vector is a convenient way to represent a single data instance or a set of features. __Feature vector__ - a list of features describing one sample. For example, if we have a patient with [height, weight, age], that’s a feature vector in 3-dimensional space. Vectors are used to represent words in NLP (word embeddings), pixel values of an image (flattened into one long vector), or a time-series of sensor readings, etc.

In [11]:
# create a vector (as a 1D numpy array)

v = np.array([2, 5, 1])
w = np.array([3, 4, 1])

print('Vector v:', v)
print('Vector w:', w)
print('Shape of v:', v.shape)

Vector v: [2 5 1]
Vector w: [3 4 1]
Shape of v: (3,)


In [14]:
# addition - add corresponding elements

print("v + w =", v + w)

v + w = [5 9 2]


In [16]:
# subtraction

print("v - w =", v - w)

v - w = [-1  1  0]


NumPy will perform __element-wise__ addition/subtraction automatically since v and w have the same shape.

In [17]:
# Scalar Multiplication: Multiply each element by a number.

print("2 * v =", 2 * v)

2 * v = [ 4 10  2]


In [19]:
# Magnitude (Length): ||v|| = sqrt(v_1^2 + v_2^2 + ... ).

mag_v = np.linalg.norm(v)    # Euclidean norm (length) of v

print("||v|| =", mag_v)

||v|| = 5.477225575051661


In [20]:
# manually it can be done

np.sqrt((v**2).sum())

5.477225575051661

---
---

#### 2. Matrices 

In linear algebra, matrices are used to solve systems of linear equations, to represent linear transformations (like rotating or scaling coordinates), and much more.

In [21]:
# create a 2 x 3 matrix
M = np.array([[1, 2, 3],
             [4, 5, 6]])

In [22]:
# first row
M[0, :]

array([1, 2, 3])

In [23]:
# 3rd column
M[:, 2]

array([3, 6])

We can do __operations__ on matrices __element-wise__ similar to vectors (addition, subtraction, scalar multiply, etc., __as long as shapes align__ or 
__via broadcasting__).

In [24]:
M * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
N = np.array([[7, 8, 9],
             [1, 2, 3]])

M + N

array([[ 8, 10, 12],
       [ 5,  7,  9]])

---

__Use in Data/ML__:

As mentioned, treating the whole dataset as a matrix allows vectorized computations. For instance, if X is an (N×M) matrix of data and w is an (M×1) weight vector, then X @ w yields an N×1 vector of predictions (one per data point). This is how we express making predictions for multiple data points in one go.