In contrast to Python lists, which can hold mixed types and are optimized for general use, NumPy arrays are __optimized for numerical operations on large volumes of data__. This means NumPy operations can often __use less memory and run much faster__ than equivalent Python code using lists.

__Why use NumPy?__ Python’s built-in lists are flexible and great for general purposes, but NumPy arrays provide __significant performance and memory advantages__ for numerical data.

---

In [1]:
import numpy as np

NumPy’s core object is the `ndarray`, a multi-dimensional array of elements (`all of the same type`).

---

### Creating NumPy Arrays


- **From Python lists/tuples:**

In [2]:
data_list = [1, 2, 3, 4]
arr = np.array(data_list)

print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4]
int32
<class 'numpy.ndarray'>


In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.shape

(4,)

This converts the list into a 1D NumPy array. Nested lists will create multi-dimensional arrays (e.g. a list of lists becomes a 2D array).

- __Using built-in array creation functions:__

    - `np.zeros(shape)` – create an array filled with 0.
    - `np.ones(shape)` – create an array filled with 1.
    - `np.full(shape, fill_value)` – create an array filled with a specified value.
    - `np.arange(start, stop, step)` – create a 1D array with a range of values (like Python’s range() but as an array). For example, np.arange(0, 10, 2) gives array [0, 2, 4, 6, 8].
    - `np.linspace(start, stop, num)` – create an array of num evenly spaced values between start and stop (inclusive).
    - `np.eye(N)` or `np.identity(N)` – create an NxN identity matrix (1s on the diagonal, 0s elsewhere). __միավոր մատրից__
    - `np.random.rand(d0, d1, ...)` – create an array of given shape with random samples from a uniform distribution on [0,1). (NumPy’s random module contains many methods for random sampling.)


---

- __Data types (dtype)__: When creating an array, NumPy will automatically choose a data type for the elements (e.g. int64, float64). You can check the data type with `arr.dtype`. You can also specify a dtype explicitly, for example np.array([1,2,3], dtype=np.float32). Common NumPy dtypes include `int64`, `float64`, `bool`, etc. Using a lower precision type (like float32 instead of float64) can save memory, but might affect numerical precision.

In [5]:
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

---

- __Array attributes__: 

    - `arr.shape` – a tuple indicating the size of each dimension (e.g. a 2D array of 3 rows and 4 columns has shape (3, 4)).
    - `arr.ndim` – number of dimensions (axes) of the array. (1D ⇒ ndim=1, 2D ⇒ ndim=2, etc.)
    - `arr.size` – total number of elements in the array (product of the shape dimensions).
    - `arr.dtype` – data type of the elements.
    - `arr.itemsize` – size in bytes of each element.
    - `arr.nbytes` – total bytes consumed by the array (nbytes = size * itemsize).


In [6]:
np.array([1, 2, 4]).ndim

1

----

One **important difference** from Python lists: **slicing a NumPy array returns a *view*, not a copy**. This means the extracted subarray uses the same memory as the original array. Modifying the slice will modify the original array as well.

In [5]:
a = np.array([9, 8, 7, 6])
b = a[1:3]
b[0] = 100
print(a)

[  9 100   7   6]


If you need an actual copy, you can use `arr.copy()` to explicitly copy the data.

---

__Stepping and reversing__:

- `arr[::2]` takes every second element.
- reverse an array by using a step of -1: `arr[::-1]`
- For a 2D array, you can reverse along a specific axis: e.g. `M[::-1, :]` reverses the rows (up-down flip), while `M[:, ::-1]` reverses the columns (left-right flip).

---

__Boolean masking__:

NumPy allows you to use boolean arrays for indexing (advanced indexing). If `mask` is a boolean array of the same shape as `arr`, then `arr[mask]` will select all elements where the mask is True. Typically, you create a mask by applying a condition on the array.

In [6]:
x = np.array([10, -3, 5, -1, 0])
negatives = x < 0    # array([False, True, False, True, False])
print(x[negatives])

[-3 -1]


In [8]:
# We can even directly do
x[x < 0] = 0
print(x)

[10  0  5  0  0]


Boolean indexing is very powerful for extracting or modifying subsets of your data without loops.

---

__Fancy indexing:__

You can also index using an array of indices.

In [9]:
y = np.array([10, 11, 12, 13])
y[[0, 3]]

array([10, 13])

In [12]:
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


M[[0, 2], [1, 2]]
# it would pick the elements at (0,1) and (2,2). 
# (Fancy indexing always returns a copy, not a view, since it may gather elements from different places in memory.)

array([2, 9])

---

#### Reshaping

In [13]:
v = np.arange(6)
v.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

You can use `-1` for one dimension in reshape to let NumPy infer it. For instance `np.arange(10).reshape(2, -1)` will reshape into 2 rows and auto-calculate the number of columns (here 5 columns).



---

__Flatten:__ To convert a multi-dimensional array to a 1D array, use `arr.ravel()` or `arr.flatten()`. `ravel()` returns a view if possible (otherwise a copy), whereas `flatten()` always returns a new copy. Example: `M.ravel()` on the 2x3 `M` above would give [0 1 2 3 4 5].

In [14]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
M.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

---

#### Arithmetic Operations and Universal Functions

NumPy allows **element-wise arithmetic** on arrays with ease. If you perform standard arithmetic operators (`+`, `-`, `*`, `/`, etc.) on arrays, it applies __element-wise__ (provided shapes are compatible, see Broadcasting). For example:

In [16]:
x = np.array([1,2,3])
y = np.array([10,20,30])
print(x + y)      
print(x * y)      
print(x ** 2)     
print(y - 5)      


[11 22 33]
[10 40 90]
[1 4 9]
[ 5 15 25]


---

NumPy also provides **universal functions (ufuncs)** which are vectorized functions that apply to each element of an array. These include mathematical functions like `np.sqrt`, `np.exp`, `np.sin`, `np.log`, etc. Using ufuncs, you can compute complex element-wise transformations without Python loops.

---

#### Broadcasting

One of NumPy’s most powerful features is **broadcasting**, which allows arithmetic operations on arrays of different shapes by automatically **stretching** the smaller array to match the larger one’s shape. Broadcasting rules apply when performing element-wise operations (like addition or multiplication) on arrays that do not have the same shape, but have compatible dimensions.

__How broadcasting works:__ When operating on two arrays, NumPy compares their shapes element by element from the __last dimension backwards__:

1. If the arrays differ in number of dimensions, the smaller array is **paded with ones** on its leading (left) side until the dimension counts match.
2. Then for each dimension, the sizes are compatible if they are equal or if one of them is 1.
3. If a dimension in one array is 1 and the other is greater than 1, NumPy will broadcast (replicate) the array along that dimension to match the size of the other array.
4. If any dimension sizes conflict (one is not 1 and not equal to the other), a broadcasting error (`ValueError`) is thrown.


In [17]:
# Example 1 (scalar and array): Adding a scalar to an array:

A = np.array([1, 2, 3])
A + 5

array([6, 7, 8])

Here, the scalar `5` is conceptually stretched to the shape of `A` (as `[5,5,5]`) and then added elementwise. NumPy does this internally without actually allocating a new array for the scalar.



In [18]:
# Example 2 (different shapes):

M = np.array([[1,2,3],
              [4,5,6]])        # shape (2,3)
v = np.array([10, 20, 30])     # shape (3,) vector 1D

In [19]:
M + v

array([[11, 22, 33],
       [14, 25, 36]])

Here `M` has shape (2,3) and `v` has shape (3,). When adding, NumPy sees that `v` is 1-dimensional. It pads `v`’s shape to (1,3) to match M’s 2D shape, then on the first dimension, 1 vs 2 means `v` is replicated to shape (2,3). Effectively, `v` is added to each row of `M`. This is much more efficient than looping to add `v` to each row manually.

In [20]:
# Example 3

a = np.array([[1],[2],[3],[4]])   # shape (4,1)
b = np.array([10,20,30])   # shape (3,)

print(a)

[[1]
 [2]
 [3]
 [4]]


In [21]:
print(b)

[10 20 30]


In [22]:
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

---

#### Random Number Generation


NumPy includes a random module (`np.random`) that can generate random numbers efficiently:

- `np.random.rand(d0, d1, ...)` – generates an array of given shape with random samples from a uniform distribution [0,1).
- `np.random.randn(d0, d1, ...)` – samples from a standard normal distribution (mean 0, std 1).
- `np.random.randint(low, high, size)` – random integers from low (inclusive) to high (exclusive).
- `np.random.choice(arr, size)` – randomly choose elements from an array.
- To reproduce results, use `np.random.seed(seed_value)` before generating random numbers.


In [29]:
np.random.seed(0)
rand_arr = np.random.rand(3, 2)
print(rand_arr)

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]


In [31]:
rand_ints = np.random.randint(5, 15, size=4) # # 1D array of 4 random ints between 5 and 14
print(rand_ints)

[13  6 11 12]


---