https://numpy.org/doc/

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]
type(mylist)

list

__`np.array()`__

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
myarr = np.array(mylist)

In [5]:
type(myarr)

numpy.ndarray

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

this is two dimensional, it's actually three rows by three columns

___

__`np.arange()`__

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

___

__`np.zeros()`__

one dimensional vector of zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# Note that these zeros are actually floating point numbers, 
# by default numpy often returns back things as floating point numbers in order to preserve some sort of precision.

a two dimensional array

In [14]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

___

__`np.ones()`__

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

___

__`np.linspace()`__

This function returns evenly (равномерно) spaced numbers over a specified interval.

In [17]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [20]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
len(np.linspace(0, 5, 21))

21

___

__`np.eye()`__

creates an identity matrix

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

___

### random distributions of data

You give it a shape and it will populate it with random samples from a uniform distribution over the points zero to one.

__<u>a uniform distribution__ means all those numbers between zero and one have the same likelihood of being picked.

__`np.random.rand()`__

In [23]:
np.random.rand(1)

# And every time you rerun the cell, you'll notice it keeps giving us back a different random number.

array([0.75258263])

In [24]:
np.random.rand(5, 3)

array([[0.80655088, 0.45600547, 0.8606741 ],
       [0.22824364, 0.05587708, 0.9307031 ],
       [0.57989621, 0.86991982, 0.17885248],
       [0.76593744, 0.87787183, 0.46269463],
       [0.9588034 , 0.01732066, 0.79444251]])

________

__<u>a standard normal distribution__ is a normal distribution where the mean is zero and the variance is one.

__`np.random.randn()`__

In [25]:
np.random.randn(10)

array([ 0.28371566,  1.03759889,  1.572919  , -0.69439176,  0.02416656,
       -1.30618259,  0.47835943, -0.26531925,  2.06012907, -0.18378539])

In [26]:
np.random.randn(2, 4)

array([[0.40533517, 0.1324149 , 1.32124879, 0.49089733],
       [0.47144298, 0.34717594, 0.03241304, 0.76924406]])

Because it's a standard normal distribution, values closer to zero are more likely to appear than values further away from zero.

___

__`np.random.randint()`__

In [27]:
# returns back random integers.
np.random.randint(0, 101, 5)

array([30, 24, 16, 50, 14])

In [28]:
np.random.randint(0, 101, (4, 3))

array([[68, 34, 30],
       [81, 65, 73],
       [79,  5, 75],
       [17, 35, 70]])

____

Something to note here is that when you're using random data and you're running different tests on it, it's very useful to be able to actually __set a seed__.

And the seed is used to set a random state so that the random results can actually be reproduced.

__`np.random.seed()`__

In [29]:
np.random.seed(42)
np.random.rand(4)

# make sure you do this in the same cell.

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

But the important thing is that if you were to copy this and run this in a new notebook somewhere or even in a different cell, as long as they're in the same cell, you'll get back those same random numbers.

___

__`.reshape() method`__

In [32]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape((5, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape((5, 4))

ValueError: cannot reshape array of size 25 into shape (5,4)

___

__`.min(), .max(), .argmin(), .argmax() methods`__

In [35]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([99, 23,  2, 21, 52,  1, 87, 29, 37,  1])

In [36]:
ranarr.max()

99

In [37]:
ranarr.min()

1

If you want to know the index location of these elements, you simply say argmin() and argmax().

In [38]:
ranarr.argmin()

5

In [39]:
ranarr.argmax()

0

___

__`.dtype`__ attribute

In [42]:
ranarr

array([99, 23,  2, 21, 52,  1, 87, 29, 37,  1])

In [43]:
ranarr.dtype

dtype('int32')

____

__`.shape`__ attribute

In [45]:
arr # one dimensional vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.shape

(25,)

In [51]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [52]:
arr = arr.reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)

___

## NumPy Indexing and Selection

In [54]:
arr = np.arange(0, 11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[8]

8

In [58]:
arr[1:5] # up to but not including

array([1, 2, 3, 4])

In [59]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [60]:
# or
arr[:5]

array([0, 1, 2, 3, 4])

In [61]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

___

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

__You would NOT be able to do this with a normal python list.__

___

In [76]:
arr = np.arange(0, 11)

In [77]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

Now, what do you think is going to happen with my original array?

That slice of the array (slice_of_arr), is arr[0:5], which means __this broadcasting operation has actually affected the original array__.

In [80]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

If you want it __to NOT have it affect the original array__, you would need to explicitly __set a copy__.

__`.copy() method`__

In [83]:
arr_copy = arr.copy()

In [84]:
print(id(arr_copy))
print(id(arr))

2550989352848
2550989350256


In [85]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [86]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

___

In [87]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [88]:
arr_2d.shape

(3, 3)

In [89]:
arr_2d[0] # first row

array([ 5, 10, 15])

In [92]:
arr_2d[-1] # last row

array([35, 40, 45])

To get a single element (for example 25)

In [93]:
# either

arr_2d[1][1]

25

In [94]:
# or

arr_2d[1, 1]

25

___

In [97]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [98]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

___

###  conditional selection

In [99]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

I can ask for where is my array greater than the number four.

In [100]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [101]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
len(arr)

10

___

### NumPy Operations

In [108]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy will perform this operation on an element by element basis

In [109]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [119]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [120]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

numpy is a little bit special in the way it deals with divisions by zero or with something like a division error.
So what actually happens is you get a warning instead of a full error.

numpy will output a result, however, it will give you a warning that some sort of invalid value was encountered during division.

In [121]:
arr / arr 

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [122]:
1 / 0

ZeroDivisionError: division by zero

In [123]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
1 / arr

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

___

In [125]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [126]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [127]:
np.log(arr)

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

___

https://docs.scipy.org/doc/numpy-1.3.x/reference/ufuncs.html

___

### summary statistics on arrays

In [130]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
arr.sum()

45

In [131]:
arr.mean()

4.5

In [132]:
arr.max()

9

In [133]:
arr.var()

8.25

In [134]:
arr.std()

2.8722813232690143

___

In [137]:
arr_2d = np.arange(0, 25).reshape(5, 5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [139]:
arr_2d.sum()

300

But let's imagine I actually want to take it the sum of all the rows or all the columns.

In [140]:
# there's an axis parameter

arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [141]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

___

get array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [142]:
np.array([5.] *10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [144]:
np.ones(10) + 4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [145]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])